name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t yzabihkeraam/docker-test:latest .

      - name: Stop and remove previous container
        run: |
          docker stop zabihkeraam/docker-test || true
          docker rm zabihkeraam/docker-test || true

      - name: Push Docker image
        run: docker push zabihkeraam/docker-test:latest

      - name: Run Docker container
        run: |
          docker run -d --name zabihkeraam/docker-test -p 80:80 zabihkeraam/docker-test:latest

      - name: Verify container
        run: docker ps

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
