name: Docker Build and Deploy


on:
  workflow_run:
    workflows: ["Terraform Plan, Apply, and Configure Instance"]
    types:
      - completed
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Add current user to Docker group
        run: |
          sudo usermod -aG docker $USER
          sudo chmod 660 /var/run/docker.sock
          sudo chown root:docker /var/run/docker.sock

      - name: Check current user
        run: |
          echo "Current user: $(whoami)"

      - name: Check user groups
        run: |
          echo "Current user groups: $(groups)"

      - name: Check Docker socket permissions
        run: |
          ls -l /var/run/docker.sock

      # Build the Docker image
      - name: Build Docker image
        run: |
          sg docker -c "docker buildx build --build-arg CONFIG=preprod --no-cache -t bitlinksai/terraform:preprod ."
        env:
          DOCKER_BUILDKIT: 1

      - name: Stop and remove previous container
        run: |
          docker stop terraform || true
          docker rm terraform || true

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push bitlinksai/terraform:preprod

      # Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d --name terraform -p 5173:5173 --restart always bitlinksai/terraform:preprod

      # Clean up untagged (dangling) images
      - name: Clean up untagged images
        run: |
          docker image prune -a -f