name: CI/CD Pipeline with Self-Hosted Runner

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t your-dockerhub-username/your-repo-name:latest .

      # Stop and remove the previous container (if running)
      - name: Stop and remove previous container
        run: |
          docker stop your-container-name || true
          docker rm your-container-name || true

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push your-dockerhub-username/your-repo-name:latest

      # Run the updated Docker container
      - name: Run Docker container
        run: |
          docker run -d --name zabihkeraam/docker-test -p 80:80 zabihkeraam/docker-test:latest

      # (Optional) Verify the container is running
      - name: Verify container
        run: docker ps

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
