name: Terraform Plan and Apply

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Use the latest stable version

      # Initialize Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Destroy existing resources (if any)
      - name: Terraform Destroy (if needed)
        id: destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Run Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Run Terraform Apply (if Plan succeeds)
      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Get Public IP
      - name: Get Public IP
        id: get-ip
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip | tr -d '\r' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
          echo "Public IP: $PUBLIC_IP"
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      # Print Public IP
      - name: Print Public IP
        run: |
          echo "The public IP is: $PUBLIC_IP"

      # Upload Public IP as Artifact
      - name: Upload Public IP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-ip
          path: ${{ env.PUBLIC_IP }}