name: Terraform Plan, Apply, and Configure Instance

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-north-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Verify S3 Bucket Access
        run: |
          aws s3api head-bucket --bucket state-bucket-webserver --region eu-north-1

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Save Terraform Outputs to File
        run: |
          echo "$(terraform output -raw instance_public_ip | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'  | sort -u)" > public_ip.txt
          echo "$(terraform output -raw private_key | tail -n +2)" > private_key.txt

      - name: Debug Files
        run: |
          ls -l
          echo "Contents of public_ip.txt:"
          cat public_ip.txt
          echo "Contents of private_key.txt:"
          cat private_key.txt

      - name: Upload Terraform Outputs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: |
            public_ip.txt
            private_key.txt

  configure:
    name: Configure Instance
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Terraform Outputs Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: ./terraform-outputs

      - name: Save Private Key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "$(cat ./terraform-outputs/private_key.txt)" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Private key saved to ~/.ssh/id_rsa"
          ls -l ~/.ssh   # Debug: Show the contents of the ~/.ssh directory
          cat ~/.ssh/id_rsa 

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          echo "Ansible installed"
          ansible --version

      - name: Debug Files
        run: |
          echo "Public IP: $(cat ./terraform-outputs/public_ip.txt)"
          echo "Private key: $(cat ./terraform-outputs/private_key.txt)"

      - name: Debug SSH KeyScan
        run: |
          echo "Public IP: $(cat ./terraform-outputs/public_ip.txt)"
          ping -c 4 $(cat ./terraform-outputs/public_ip.txt)
          ssh-keyscan -H $(cat ./terraform-outputs/public_ip.txt)

      - name: Debug Ansible Inventory File
        run: |
          echo "Contents of Ansible inventory.ini:"
          cat ./ansible/inventory.ini
      - name: Debug SSH Directory
        run: |
          echo "Contents of ~/.ssh:"
          ls -l ~/.ssh
      - name: Prepare Ansible files
        run: |
          mkdir -p ansible
          cp ./ansible-playbook.yml ./ansible/
          echo "[servers]" > ./ansible/inventory.ini
          echo "$(cat ./terraform-outputs/public_ip.txt) ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ./ansible/inventory.ini
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $(cat ./terraform-outputs/public_ip.txt) >> ~/.ssh/known_hosts
          echo "Ansible files prepared"
          ls -l ./ansible
          cat ./ansible/inventory.ini

      - name: Debug Ansible Inventory File
        run: |
          echo "Contents of Ansible inventory.ini:"
          cat ./ansible/inventory.ini

      - name: Debug Files
        run: |
          echo "Public IP: $(cat ./terraform-outputs/public_ip.txt)"
          echo "Private key: $(cat ./terraform-outputs/private_key.txt)"
          echo "Id rsa key: $(cat ~/.ssh/id_rsa)"

      - name: Run Ansible Playbook
        run: |
          cd ansible
          echo "Current directory: $(pwd)"
          ls -l 
          ansible-playbook -i inventory.ini ansible-playbook.yml --user ubuntu --private-key ~/.ssh/id_rsa

      - name: Securely Delete Private Key
        if: always()
        run: |
          shred -u ~/.ssh/id_rsa