name: Terraform Plan, Apply, and Configure Instance

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Save Terraform Outputs to File
        run: |
          echo "$(terraform output -raw instance_public_ip)" > public_ip.txt
          echo "$(terraform output -raw private_key)" > private_key.txt

      - name: Create Shared Directory and Set Permissions
        run: |
          # Create the shared directory
          sudo mkdir -p /opt/shared_data/
      
          # Set permissions to ensure it is accessible by all users
          sudo chown root:root /opt/shared_data/
          sudo chmod 777 /opt/shared_data/
        
      - name: Copy Files to Shared Directory
        run: |
          # Copy the files to /opt/shared_data/
          sudo cp public_ip.txt /opt/shared_data/
          sudo cp private_key.txt /opt/shared_data/
      
          # Verify the files are copied
          ls -l /opt/shared_data/

      - name: Debug Files
        run: |
          ls -l
          cat public_ip.txt
          cat private_key.txt

      - name: Authenticate GitHub CLI
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Use the PAT stored in GitHub Secrets
        run: |
          echo "$GH_PAT" | gh auth login --with-token

      - name: Save Outputs to GitHub Secrets
        run: |
          gh secret set PUBLIC_IP --body "$(cat public_ip.txt)"
          gh secret set PRIVATE_KEY --body "$(cat private_key.txt)"

  configure:
    name: Configure Instance
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use shared Secrets
        run: |
          sudo cat /opt/shared_data/public_ip.txt
          sudo cat /opt/shared_data/private_key.txt


      - name: Save Private Key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Private key saved to ~/.ssh/id_rsa"
          ls -l ~/.ssh   # Debug: Show the contents of the ~/.ssh directory
          cat ~/.ssh/id_rsa 

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          echo "Ansible installed"
          ansible --version  # Debug: Show the installed Ansible version

      - name: Prepare Ansible files
        run: |
          mkdir -p ansible
          cp ./ansible-playbook.yml ./ansible/
          echo "[webservers]" > ./ansible/hosts
          echo "${{ secrets.PUBLIC_IP }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ./ansible/hosts
          echo "Ansible files prepared"
          ls -l ./ansible   # Debug: Show the contents of the ansible directory
          cat ./ansible/hosts   # Debug: Show the contents of the hosts file
      - name: Debug PUBLIC_IP
        run: |
          echo "Public IP: ${{ secrets.PUBLIC_IP }}"
          echo "Private key: ${{ secrets.PRIVATE_KEY }}"
      - name: Run Ansible Playbook
        run: |
          cd ansible
          echo "Current directory: $(pwd)"
          ls -l 
          ansible-playbook -i hosts ansible-playbook.yml --user ubuntu --private-key ~/.ssh/id_rsa

      - name: Securely Delete Private Key
        if: always()
        run: |
          shred -u ~/.ssh/id_rsa